### ISSUE TITLE
[question]May I ask questions for device tree?

### ISSUE THREAD

**Issue by skysumbra** [physwizz/M04-twrp#1]
Hi [physwizz](https://github.com/physwizz)
I was practice twrp general tree  for pixel 7 phone,may I ask questions for device tree?

**Comment by physwizz** [comment]
Yes

**Comment by skysumbra** [comment]
Very Very Very thanks [physwizz](https://github.com/physwizz)
I have some question.
 * [ ] **Question 1. what's  twrp version use ?**

Practice target device:Google pixel 7
OS: android 13


Could i use [platform_manifest_twrp_aosp](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp) 12.1 version ? I sync this code in my virtual machine  on last month.

```
repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
```

Or use this [omnirom android](https://github.com/omnirom/android)
```
repo init -u https://github.com/omnirom/android.git -b android-13.0
```

**Comment by physwizz** [comment]
I've been using the Android 11 manifest.

https://t.me/a127f_res/204

I Use  Linux Mint Mate in a virtual box on my mac with 3gb Ram and 8gb swapfile

**Comment by skysumbra** [comment]
> I've been using the Android 11 manifest.
> 
> https://t.me/a127f_res/204
> 
> I Use Linux Mint Mate in a virtual box on my mac with 3gb Ram and 8gb swapfile


* [x] **Question 1. what's twrp version use ?**
Let me try twrp banch 12.1 after completed device tree.

**Comment by skysumbra** [comment]
**Question 2. How to write correct device tree**
Last month, I was used [twrpdtgen](https://github.com/twrpdtgen/twrpdtgen) tool generate device tree.

* [ ] 1. Where correct device kernel ?
Pixel 7 phone not exist recovery img, so i try use `boot` ,`vendor_boot` and `vendor_kernel_boot_a` partition.
Got those information on last month.

```
user@user-VirtualBox:~/Desktop/AIK-Linux-mirror-master$ ./unpackimg.sh boot_a.img 
Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers
 
Supplied image: boot.img
 
Setting up work folders...
 
Image type: AOSP
 
Signature with "AVBv2" type detected.
 
Splitting image to "split_img/"...
ANDROID! magic found at: 0
BOARD_KERNEL_CMDLINE 
BOARD_PAGE_SIZE 4096
BOARD_HEADER_VERSION 4
BOARD_HEADER_SIZE 1584
 
Warning: No ramdisk found to be unpacked!
 
Done!
```
```
user@user-VirtualBox:~/Desktop/AIK-Linux-mirror-master$ ./unpackimg.sh vendor_boot_a.img 
Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers
 
Supplied image: vendor_boot_a.img
 
Setting up work folders...
 
Image type: AOSP_VNDR
 
Signature with "AVBv2" type detected.
 
Splitting image to "split_img/"...
VNDRBOOT magic found at: 0
BOARD_VENDOR_CMDLINE swiotlb=noforce dyndbg="func alloc_contig_dump_pages +p" earlycon=exynos4210,0x10A00000 console=ttySAC0,115200 androidboot.console=ttySAC0 printk.devkmsg=on cma_sysfs.experimental=Y cgroup_disable=memory rcupdate.rcu_expedited=1 rcu_nocbs=all stack_depot_disable=off page_pinner=on swiotlb=1024 disable_dma32=on at24.write_timeout=100 log_buf_len=1024K bootconfig
BOARD_VENDOR_BASE 0x10000000
BOARD_NAME 
BOARD_PAGE_SIZE 2048
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x01000000
BOARD_TAGS_OFFSET 0x00000100
BOARD_HEADER_VERSION 4
BOARD_HEADER_SIZE 2128
BOARD_DTB_SIZE 0
BOARD_DTB_OFFSET 0x01f00000
 
Unpacking ramdisk (as root) to "ramdisk/"...
 
Compression used: lz4-l
80282 blocks
 
Done!
```

```
./unpackimg.sh vendor_kernel_boot_a.img 
Android Image Kitchen - UnpackImg Script
by osm0sis @ xda-developers
 
Supplied image: vendor_kernel_boot_a.img
 
Setting up work folders...
 
Image type: AOSP_VNDR
 
Signature with "AVBv2" type detected.
 
Splitting image to "split_img/"...
VNDRBOOT magic found at: 0
BOARD_VENDOR_CMDLINE 
BOARD_VENDOR_BASE 0x10000000
BOARD_NAME 
BOARD_PAGE_SIZE 2048
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x01000000
BOARD_TAGS_OFFSET 0x00000100
BOARD_HEADER_VERSION 4
BOARD_HEADER_SIZE 2128
BOARD_DTB_SIZE 580030
BOARD_DTB_OFFSET 0x01f00000
 
Unpacking ramdisk (as root) to "ramdisk/"...
 
Compression used: lz4-l
41406 blocks
 
Done!
```
Content
```
user@user-VirtualBox:~/Desktop/AIK-Linux-mirror-master$ ls -alh ./boot/split_img/
total 24M
drwxrwxr-x 2 user user 4.0K  四  29 21:01 .
drwxrwxr-x 4 user user 4.0K  四  29 21:01 ..
-rw-rw-r-- 1 user user    1  四  29 21:01 boot.img-cmdline
-rw-rw-r-- 1 user user    3  四  29 21:01 boot.img-header_version
-rw-rw-r-- 1 user user    5  四  29 21:01 boot.img-imgtype
-rw-rw-r-- 1 user user  24M  四  29 21:01 boot.img-kernel
-rw-rw-r-- 1 user user    9  四  29 21:01 boot.img-origsize
-rw-rw-r-- 1 user user    5  四  29 21:01 boot.img-os_patch_level
-rw-rw-r-- 1 user user    6  四  29 21:01 boot.img-os_version
-rw-rw-r-- 1 user user    6  四  29 21:01 boot.img-ramdiskcomp
-rw-rw-r-- 1 user user    0  四  29 21:01 boot.img-ramdisk.cpio.empty
-rw-rw-r-- 1 user user    6  四  29 21:01 boot.img-sigtype
user@user-VirtualBox:~/Desktop/AIK-Linux-mirror-master$ 
```
```
user@user-VirtualBox:~/Desktop/AIK-Linux-mirror-master$ ls -alh ./vendor_boot_a/split_img/
total 22M
drwxrwxr-x 2 user user 4.0K  四  29 21:01 .
drwxrwxr-x 4 user user 4.0K  四  29 21:11 ..
-rw-rw-r-- 1 user user   11  四  29 21:01 vendor_boot_a.img-base
-rw-rw-r-- 1 user user    1  四  29 21:01 vendor_boot_a.img-board
-rw-rw-r-- 1 user user    0  四  29 21:01 vendor_boot_a.img-dtb
-rw-rw-r-- 1 user user   11  四  29 21:01 vendor_boot_a.img-dtb_offset
-rw-rw-r-- 1 user user    3  四  29 21:01 vendor_boot_a.img-header_version
-rw-rw-r-- 1 user user   10  四  29 21:01 vendor_boot_a.img-imgtype
-rw-rw-r-- 1 user user   11  四  29 21:01 vendor_boot_a.img-kernel_offset
-rw-rw-r-- 1 user user    9  四  29 21:01 vendor_boot_a.img-origsize
-rw-rw-r-- 1 user user    5  四  29 21:01 vendor_boot_a.img-pagesize
-rw-rw-r-- 1 user user   11  四  29 21:01 vendor_boot_a.img-ramdisk_offset
-rw-rw-r-- 1 user user    6  四  29 21:01 vendor_boot_a.img-sigtype
-rw-rw-r-- 1 user user   11  四  29 21:01 vendor_boot_a.img-tags_offset
-rw-rw-r-- 1 user user  364  四  29 21:01 vendor_boot_a.img-vendor_cmdline
-rw-rw-r-- 1 user user    6  四  29 21:01 vendor_boot_a.img-vendor_ramdiskcomp
-rw-rw-r-- 1 user user  21M  四  29 21:01 vendor_boot_a.img-vendor_ramdisk.cpio.lz4
user@user-VirtualBox:~/Desktop/AIK-Linux-mirror-master$ 

```
```
user@user-VirtualBox:~/Desktop/AIK-Linux-mirror-master$ ls -alh ./vendor_kernel_boot_a/split_img/
total 6.6M
drwxrwxr-x 2 user user 4.0K  四  29 21:12 .
drwxrwxr-x 4 user user 4.0K  四  29 21:14 ..
-rw-rw-r-- 1 user user   11  四  29 21:12 vendor_kernel_boot_a.img-base
-rw-rw-r-- 1 user user    1  四  29 21:12 vendor_kernel_boot_a.img-board
-rw-rw-r-- 1 user user 567K  四  29 21:12 vendor_kernel_boot_a.img-dtb
-rw-rw-r-- 1 user user   11  四  29 21:12 vendor_kernel_boot_a.img-dtb_offset
-rw-rw-r-- 1 user user    3  四  29 21:12 vendor_kernel_boot_a.img-header_version
-rw-rw-r-- 1 user user   10  四  29 21:12 vendor_kernel_boot_a.img-imgtype
-rw-rw-r-- 1 user user   11  四  29 21:12 vendor_kernel_boot_a.img-kernel_offset
-rw-rw-r-- 1 user user    9  四  29 21:12 vendor_kernel_boot_a.img-origsize
-rw-rw-r-- 1 user user    5  四  29 21:12 vendor_kernel_boot_a.img-pagesize
-rw-rw-r-- 1 user user   11  四  29 21:12 vendor_kernel_boot_a.img-ramdisk_offset
-rw-rw-r-- 1 user user    6  四  29 21:12 vendor_kernel_boot_a.img-sigtype
-rw-rw-r-- 1 user user   11  四  29 21:12 vendor_kernel_boot_a.img-tags_offset
-rw-rw-r-- 1 user user    1  四  29 21:12 vendor_kernel_boot_a.img-vendor_cmdline
-rw-rw-r-- 1 user user    6  四  29 21:12 vendor_kernel_boot_a.img-vendor_ramdiskcomp
-rw-rw-r-- 1 user user 6.0M  四  29 21:12 vendor_kernel_boot_a.img-vendor_ramdisk.cpio.lz4
```


kernel:boot.img-kernel from boot ??
dtb:vendor_kernel_boot_a.img-dtb from vendor_kernel_boot_a ??
put fils in /prebuilt

Anything else ? I am not sure.


I was update file on [there](https://gitlab.com/besov007/test/-/tree/main/prebuilt).

**Comment by physwizz** [comment]
Kernel should be in boot.img split Image 

rw-rw-r-- 1 user user 24M 四 29 21:01 boot.img-kernel

**Comment by skysumbra** [comment]
> Kernel should be in boot.img split Image
> 
> rw-rw-r-- 1 user user 24M 四 29 21:01 boot.img-kernel

**Question 2. How to write correct device tree?**
* [x] 1.Where correct device kernel ?

I was found this [Vendor_Boot ROMs](https://forum.xda-developers.com/t/vendor_boot-roms.4575777/) webpage on XDA forum.
Maybe device is **vendor_boot-as-recovery** structure.
In this practice, maybe put ` boot.img-kernel`,  and dtb `vendor_kernel_boot_a.img-dtb`  file in  /prebuilt folder.
boot.img-kernel -> kernel
vendor_kernel_boot_a.img-dtb -> dtb.img
I guess...

**Comment by skysumbra** [comment]
**Question 2. How to write correct device tree?**
* [x] 1.Where correct device kernel ?
* [x] 2.[Twrpdtgen](https://github.com/twrpdtgen/twrpdtgen#twrpdtgen) tool create general tree.

I got some error after `boot` and `vendor_kernel_boot_a` img.
```
[INFO] Cloning AIK...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.6/site-packages/twrpdtgen/__main__.py", line 55, in <module>
    recovery_ramdisk=args.recovery_ramdisk, recovery_vendor=args.recovery_vendor)
  File "/home/user/.local/lib/python3.6/site-packages/twrpdtgen/device_tree.py", line 57, in __init__
    raise AssertionError("Couldn't find any build.prop")
AssertionError: Couldn't find any build.prop
```
Only `vendor_boot_a` result is pass in this practice. 

Original content
```
user@user-VirtualBox:~/twrp/output_vendor_boot_a.img/google/panther$ tree -h
.
├── [ 834]  Android.mk
├── [ 771]  AndroidProducts.mk
├── [2.8K]  BoardConfig.mk
├── [1.4K]  device.mk
├── [1.5K]  omni_panther.mk
├── [4.0K]  prebuilt
│   └── [   0]  dtb.img
├── [4.0K]  recovery
│   └── [4.0K]  root
│       ├── [ 239]  android.hardware.health-service.gs201_recovery.rc
│       ├── [ 432]  init.recovery.gs201.rc
│       ├── [  46]  init.recovery.panther.rc
│       └── [ 124]  servicemanager.recovery.rc
├── [2.4K]  recovery.fstab
└── [ 786]  vendorsetup.sh

3 directories, 12 files

```
Maybe device tree use this result, and i was upload [there](https://gitlab.com/besov007/test/-/tree/main/) on last month.

**Comment by skysumbra** [comment]
**Question 2. How to write correct device tree?**
* [x] 1.Where correct device kernel ?
* [x] 2.[Twrpdtgen](https://github.com/twrpdtgen/twrpdtgen#twrpdtgen) tool create general tree.
* [ ] 3.How to modify general tree?

I find it difficult, please help review this [device tree](https://gitlab.com/besov007/test/-/tree/main/)
Is this structure correct ?

1.file 1: omni_panther.mk
I was rename omni_panther.mk file to twrp_panther.mk.

Original content
```
# Inherit from those products. Most specific first.
$(call inherit-product, $(SRC_TARGET_DIR)/product/core_64_bit.mk)
$(call inherit-product-if-exists, $(SRC_TARGET_DIR)/product/embedded.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base_telephony.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/languages_full.mk)

# Inherit from panther device
$(call inherit-product, device/google/panther/device.mk)

# Inherit some common Omni stuff.
$(call inherit-product, vendor/omni/config/common.mk)
$(call inherit-product, vendor/omni/config/gsm.mk)

# Device identifier. This must come after all inclusions
PRODUCT_DEVICE := panther
PRODUCT_NAME := omni_panther
PRODUCT_BRAND := google
PRODUCT_MODEL := google
PRODUCT_MANUFACTURER := google
PRODUCT_RELEASE_NAME := google google
```

[twrp_panther.mk](https://gitlab.com/besov007/test/-/blob/main/twrp_panther.mk)
```
# Inherit from those products. Most specific first.
$(call inherit-product, $(SRC_TARGET_DIR)/product/core_64_bit.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base_telephony.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/languages_full.mk)

# Inherit some common Omni stuff.
$(call inherit-product, vendor/twrp/config/common.mk)

# Inherit from panther device
$(call inherit-product, device/google/panther/device.mk)

PRODUCT_DEVICE := panther
PRODUCT_NAME := twrp_panther
PRODUCT_BRAND := Android
PRODUCT_MODEL := Pixel 7
PRODUCT_MANUFACTURER := google

#PRODUCT_GMS_CLIENTID_BASE := android-google
```
Is correct content if i modify it?

**Comment by physwizz** [comment]
I have only done Samsung but my instructions are here
https://t.me/a127f_res/204

**Comment by skysumbra** [comment]
> I have only done Samsung but my instructions are here
> https://t.me/a127f_res/204

let me imitate BoardConfig.mk file

**Comment by skysumbra** [comment]
I have question about recovery.fstab and twrp.flags
[Twrpdtgen](https://github.com/twrpdtgen/twrpdtgen#twrpdtgen) tool got recovery.fstab in  out folder <factory/device> path
recovery.fstab content:
```
# mount point       fstype    device                                                                flags
/system             ext4      system                                                                flags=display="System";backup=1;logical;
/system_image       emmc      system                                                                flags=display="System image";backup=1;flashimg=1;logical;
/system_dlkm        ext4      system_dlkm                                                           flags=display="System_dlkm";logical;
/system_ext         ext4      system_ext                                                            flags=display="System_ext";backup=1;logical;
/system_ext_image   emmc      system_ext                                                            flags=display="System_ext image";backup=1;flashimg=1;logical;
/product            ext4      product                                                               flags=display="Product";backup=1;logical;
/product_image      emmc      product                                                               flags=display="Product image";backup=1;flashimg=1;logical;
/vendor             ext4      vendor                                                                flags=display="Vendor";backup=1;logical;
/vendor_image       emmc      vendor                                                                flags=display="Vendor image";backup=1;flashimg=1;logical;
/vendor_dlkm        ext4      vendor_dlkm                                                           flags=display="Vendor_dlkm";logical;
/boot               emmc      /dev/block/platform/14700000.ufs/by-name/boot                         flags=display="Boot";backup=1;flashimg=1;
/init_boot          emmc      /dev/block/platform/14700000.ufs/by-name/init_boot                    flags=display="Init_boot";
/misc               emmc      /dev/block/platform/14700000.ufs/by-name/misc                         flags=display="Misc";backup=1;flashimg=1;
/metadata           f2fs      /dev/block/platform/14700000.ufs/by-name/metadata                     flags=display="Metadata";
/data               f2fs      /dev/block/platform/14700000.ufs/by-name/userdata                     flags=display="Data";
/vbmeta             emmc      /dev/block/platform/14700000.ufs/by-name/vbmeta                       flags=display="Vbmeta";
/11210000.usb*      auto      vfat                                                                  flags=display="11210000.usb*";logical;
```
but look this content inside ,i guess to do flag ??
could i need rename file to twrp.flags??

In addition,i got recovery.fstab if i find `vendor_boot_a/ramdisk/system/etc` path

Content:
```
# Android fstab file.
#
# The filesystem that contains the filesystem checker binary (typically /system) cannot
# specify MF_CHECK, and must come before any filesystems that do specify MF_CHECK
#
#<src>                                                   <mnt_point>                 <type>  <mnt_flags and options>  <fs_mgr_flags>
system                                                   /system                     ext4    ro                       wait,slotselect,avb=vbmeta_system,logical,first_stage_mount,readahead_size_kb=128
system_dlkm                                              /system_dlkm                ext4    ro                       wait,slotselect,avb=vbmeta_system,logical,first_stage_mount,readahead_size_kb=128
system_ext                                               /system_ext                 ext4    ro                       wait,slotselect,avb=vbmeta_system,logical,first_stage_mount,readahead_size_kb=128
product                                                  /product                    ext4    ro                       wait,slotselect,avb=vbmeta_system,logical,first_stage_mount,readahead_size_kb=128
vendor                                                   /vendor                     ext4    ro                       wait,slotselect,avb=vbmeta_vendor,logical,first_stage_mount,readahead_size_kb=128
vendor_dlkm                                              /vendor_dlkm                ext4    ro                       wait,slotselect,avb=vbmeta,logical,first_stage_mount
/dev/block/platform/14700000.ufs/by-name/boot            /boot                       emmc    defaults                 slotselect,avb=boot,first_stage_mount
/dev/block/platform/14700000.ufs/by-name/init_boot       /init_boot                  emmc    defaults                 slotselect,avb=init_boot,first_stage_mount
/dev/block/platform/14700000.ufs/by-name/misc            /misc                       emmc    defaults                 wait
/dev/block/platform/14700000.ufs/by-name/metadata        /metadata                   f2fs    noatime,nosuid,nodev,sync  wait,check,formattable,first_stage_mount
#/dev/block/platform/14700000.ufs/by-name/pvmfw           /pvmfw                      emmc    defaults                 wait,slotselect,avb=pvmfw,first_stage_mount
/dev/block/platform/14700000.ufs/by-name/userdata        /data                       f2fs    noatime,nosuid,nodev,discard,reserve_root=32768,resgid=1065,fsync_mode=nobarrier,inlinecrypt,atgc,checkpoint_merge,compress_cache    latemount,wait,check,quota,formattable,sysfs_path=/dev/sys/block/bootdevice,checkpoint=fs,reservedsize=128M,fileencryption=::inlinecrypt_optimized+wrappedkey_v0,metadata_encryption=:wrappedkey_v0,keydirectory=/metadata/vold/metadata_encryption,fscompress,readahead_size_kb=128
/dev/block/platform/14700000.ufs/by-name/vbmeta          /vbmeta                     emmc    defaults                 slotselect,first_stage_mount
/devices/platform/11210000.usb*                          auto                        vfat    defaults                 voldmanaged=usb:auto
```
 Is this `recovery.fstab` really file?
And if items are missing, how do I fill them in?

**Comment by physwizz** [comment]
Read my instructions 

TWRP Building for a12s
=============
Taken from here
https://t.me/physwizz2/398

1. Setup
--------

sudo apt update
sudo apt upgrade
sudo apt-get install git-all

sudo apt install python-is-python3
sudo apt install python3-pip

git config --global user.email "your email"
git config --global user.name "your name"


2. swapfile
-----------

sudo swapoff -a

sudo dd if=/dev/zero of=/swapfile bs=1G count=8
sudo mkswap /swapfile
sudo swapon /swapfile

free -m

3. repo
-------

mkdir -p ~/.bin
PATH="${HOME}/.bin:${PATH}"
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
chmod a+rx ~/.bin/repo




Basic Device Tree
==================

mkdir ~/TWRP
cd ~/TWRP
git init
git clone https://github.com/twrpdtgen/twrpdtgen
pip3 install twrpdtgen
sudo apt install cpio


copy stock recovery.img to ~/TWRP/twrpdtgen

cd twrpdtgen
python3 -m twrpdtgen recovery.img

rename ~/TWRP/twrpdtgen/output/samsung/a12s/omni_a12s.mk to twrp_a12s.mk

delete vendorsetup.sh
Make a copy of recovery.fstab and rename to twrp.flags
Move both files recovery.fstab and twrp.flags to recovery/root/system/etc
(create these folders)

open twrp_a12s.mk and 
1. delete the 3 lines below # Inherit from those products, Most specific first.
replace those 3 lines with this
$(call inherit-product, $(SRC_TARGET_DIR)/product/aosp_base.mk)

2. delete $(call inherit-product, vendor/omni/config/gsm.mk)
3. change omni to twrp (2 places)

open AndroidProducts.mk
change omni to twrp (4 spots)

Add to recovery.fstab
-----------------------------------

# extra partitions 
==================

/system_image  emmc  /dev/block/mapper/system  flags=backup=0;flashimg=1;display="System Image"

/vendor_image  emmc  /dev/block/mapper/vendor  flags=backup=0;flashimg=1;display="Vendor Image"

/product_image  emmc  /dev/block/mapper/product  flags=backup=0\;flashimg=1\;display=\"Product Image\"";

/odm_image  emmc  /dev/block/mapper/odm  flags=backup=0;flashimg=1;display="Odm Image"



Add to boardconfig.mk
--------------------
TW_NO_SCREEN_TIMEOUT := true

TW_DEVICE_VERSION := 1_physwizz


To save space
-------------
if not u have to compress kernel image or reduce the size of kernel
BOARD_RAMDISK_USE_LZMA := true
LZMA_RAMDISK_TARGETS := recovery

To save more space
BOARD_HAS_NO_REAL_SDCARD := true

it will remove sd card partitioning and save some space



Establish Android Building Environment
=======================================

cd ~
sudo apt install git aria2 -y
git clone https://gitlab.com/OrangeFox/misc/scripts
cd scripts
sudo bash setup/android_build_env.sh
sudo bash setup/install_android_sdk.sh


TWRP 11
=======

mkdir ~/twrp-11

cd ~/twrp-11

repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11

repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j4


* copy ~/TWRP/twrpdtgen/output/samsung 
to /twrp-11/device/samaung 

TWRP 12
=======

mkdir ~/twrp-12

cd ~/twrp-12

repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j4


* copy ~/TWRP/twrpdtgen/output/samsung 
to twrp-12/device/samsung


Orange fox
==========

mkdir ~/OrangeFox_sync
cd ~/OrangeFox_sync

git clone https://gitlab.com/OrangeFox/sync.git

cd ~/OrangeFox_sync/sync/

./orangefox_sync.sh --branch 11.0 --path ~/fox_11.0


* copy ~/TWRP/twrpdtgen/output/samsung to /fox_11.0/device/samsung

*** For SHRP go here
https://t.me/a127f_res/275


Building
========


. build/envsetup.sh
lunch twrp_a12s-eng
mka recoveryimage -j4






Recovery.img at out/Samsung/a12s/...img


Note: I got this to work on a virtual box with 3gb ram and 8gb swapfile

To Add Things To Your Twrp, You Can Find Them On Experienced Dev's Githubs.
For Example

https://github.com/topser9

https://github.com/mohammad92

https://github.com/crazo7924

@physwizz

**Comment by physwizz** [comment]
Make a copy of recovery.fstab and rename it twrp.flags

**Comment by skysumbra** [comment]
Device is vendor_boot as recovery, so i compile TWRP using the following command

ccache -M 30G;
. build/envsetup.sh;lunch twrp_panther-eng;mka vendorbootimage -j8

terminal result
```
[ 78% 246/312] including bootable/recovery/Android.mk ...

bootable/recovery/prebuilt/Android.mk:437: warning: vendor_hw:  bootable/recovery/prebuilt/relink.sh out/target/product/panther/recovery/root/vendor/bin/hw 

[ 99% 311/312] finishing build rules ...

build/make/core/Makefile:4131: warning: Neither INSTALLED_KERNEL_TARGET nor INSTALLED_BOOTIMAGE_TARGET is defined when PRODUCT_OTA_ENFORCE_VINTF_KERNEL_REQUIREMENTS  is true. Information about the updated kernel cannot be built into OTA update package. You can fix this by: (1) setting TARGET_NO_KERNEL to false and installing the built kernel to out/target/product/panther/kernel, so that kernel information will be extracted from the built kernel; or (2) Add a prebuilt boot image and specify it in BOARD_PREBUILT_BOOTIMAGE; or (3) extracting kernel configuration and defining BOARD_KERNEL_CONFIG_FILE and BOARD_KERNEL_VERSION manually; or (4) unsetting PRODUCT_OTA_ENFORCE_VINTF_KERNEL_REQUIREMENTS manually.

FAILED: ninja: 'device/google/panther/system.prop', needed by 'out/target/product/panther/system/build.prop', missing and no known rule to make it

10:55:42 ninja failed with: exit status 1



#### failed to build some targets (35:19 (mm:ss)) ####
```

How can i fix the error ? 
thank you.

**Comment by physwizz** [comment]
Build.prop missing

**Comment by physwizz** [comment]
Needs custom kernel

**Comment by skysumbra** [comment]
let me try some value for system.prop 


> Needs custom kernel

Custom kernel ? but i don't get this kernel codebase for this pixel 7 phone.

**Comment by physwizz** [comment]
Try the kernel from your firmware
